### PR TITLE
Add Anticamper from zCatch

### LINKED ISSUE #44: Add anti camper (for the memes)

### PR DESCRIPTION
**Pull request by M0REKZ**
Add anticamper support taken from zcatch, however unlike zcatch, now it is in the character source file, it makes more sense since everything needed is there.

May need some improvements...

Closes #44

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Thanks for working on this.

One of the goals of ddnet-insta is to stay up to date with ddnet. And because of that we should always try to keep the git conflict surface low. Files that also exist in the ddnet code base like character.cpp should only be edited if there is no other option.

I did not test it but I think it should be possible to have the anti camp code in the instagib controller instead of character.cpp.

**Comment by M0REKZ** [comment]
As i can see, character.cpp is already edited with a `ResetInstaSettings()` function, maybe i can just move the anticamper variables in the header below `// ddnet-insta` comment so things are in place.

**Comment by ChillerDragon** [comment]
> As i can see, character.cpp is already edited with a `ResetInstaSettings()` function, maybe i can just move the anticamper variables in the header below `// ddnet-insta` comment so things are in place.

Yes if we have to edit character.h and character.cpp it should go to the other ddnet-insta changes. But I still think we can avoid editing character.cpp. You should be able to get a players position and freeze it from outside of the character class. Then it can live in a [base_instagib.cpp](https://github.com/ddnet-insta/ddnet-insta/blob/5e4c569e679a25e354e0f774ff01c331edcc6d80/src/game/server/gamemodes/base_instagib.cpp).

**Comment by M0REKZ** [comment]
Moved the anticamper to base_instagib and /instagib/player.h

**Comment by ChillerDragon** [comment]
Nice thanks! Next time you could also run the scripts/fix_style.py script so the indentation is correct and the pipeline passes. But don't worry I will do it for you now.

**Comment by M0REKZ** [comment]
> Nice thanks! Next time you could also run the scripts/fix_style.py script so the indentation is correct and the pipeline passes. But don't worry I will do it for you now.

Ill try to do it next time xD, i get an error about clang-format 10 missing

**Comment by ChillerDragon** [comment]
Yea you gotta install that to your PATH. How to install it depends on your system.

**Pull request merged**
