### PR TITLE
change client score kind sent to master server from "time" to "points"

### PR DESCRIPTION
**Pull request by jxsl13**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by jxsl13** [comment]
should fix #81

**Comment by ChillerDragon** [comment]
Would be even nicer if this would be supported by ddnet directly. If the time score flag is not set. So we do not touch code that might cause git conflicts. I would prefer trying to pullrequest that upstream before adding it to ddnet-insta.

**Comment by jxsl13** [comment]
bruh, all I wanted is this, not https://github.com/ddnet/ddnet/issues/7777
xD

**Comment by ChillerDragon** [comment]
> bruh, all I wanted is this, not [ddnet#7777](https://github.com/ddnet/ddnet/issues/7777) xD

Yea sorry. I hope you can wait a bit c:
If this all blows up I just merge yours :D

**Comment by jxsl13** [comment]
well, I fixed it in my server status bot by looking at the game type (suboptimal) and deduce whether it's a `points` or `time` score type.
This is now low priority.

**Comment by jxsl13** [comment]
I guess it's time to reopen this.

**Comment by ChillerDragon** [comment]
Yes it is.

**Comment by ChillerDragon** [comment]
I will give this one a go. Since ddnet now official does not support forks we have to come up with some tactics for maintaining git conflicts.

**Pull request closed without merging**
